#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "My Gentoo kernel 3.2.1 " {
     set root=(hd0,msdos1)
     echo    'Loading Linux 3.2.1-gentoo ...'
     linux /vmlinuz-3.2.1-hc-gt-kernel  root=/dev/sda3 rootfstype=ext4  video=vesafb:mtrr:3,ywrap vga=786  quiet
}

